Add steps to clean and create remote directory in deployment workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,6 +21,23 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Clean Remote Directory
+        run: |
+          curl -X DELETE \
+          --basic \
+          --user "${{ secrets.WEBDAV_USERNAME }}:${{ secrets.WEBDAV_PASSWORD }}" \
+          -L -v \
+          --url "${{ secrets.WEBDAV_URL }}/findWordsWithKnownLetters/" \
+          -f || echo "Directory doesn't exist or already deleted"
+      - name: Create Remote Directory
+        run: |
+          curl -X MKCOL \
+          --basic \
+          --user "${{ secrets.WEBDAV_USERNAME }}:${{ secrets.WEBDAV_PASSWORD }}" \
+          -L -v \
+          --url "${{ secrets.WEBDAV_URL }}/findWordsWithKnownLetters/" \
+          -f || echo "Failed to create directory, might already exist"
+
       - name: Deploy to WebDAV
         uses: XPH0816/webdav-deploy-action@v0.3
         with:
